### ISSUE TITLE
How to capture new TPMS data

### ISSUE THREAD

**Issue by StavJi** [gcormier/tpms_silencer#1]
Hello,

trying to decode raw data using rtl_433 SW. This is what I am sending: "111111001100110101010101010101010100101010110100110101001011001010101101010100101010101101010100110011010011010010101011010101001100110100101100"

On picture what I am decoding. I noticed that rtl trying to use PWM modulations but it should be FSK. Can you explain to me how to get back to your data? I supposed that you somehow captured TPMS message from car and I want to know how did you do that? Thank you for your help.

![TPMS](https://user-images.githubusercontent.com/54151419/98471539-4b58ab00-21ed-11eb-828d-ff7f049e86a3.png)

**Comment by gcormier** [comment]
I captured using rtl_433 - https://github.com/merbanan/rtl_433/issues/821

I merely replay the encoded bitstream with tpms_silencer - I don't do any actual Manchester encoding on the transmitter. So you will want the raw-bitstream from rtl_433.

**Comment by StavJi** [comment]
I figure it out, problem was that your sensors uses baudrate of 10000 so to capture raw bitstream using rtl_433 you need to use command: rtl_433 -R 0 -X "n=tpms,m=FSK_PCM,s=100,l=100,r=250". I think more common (my case) is sensors with baudrate 20000 so cmd will be: rtl_433 -R 0 -X "n=tpms,m=FSK_PCM,s=52,l=52,r=150".
