### ISSUE TITLE
Transmitter components for 433MHz

### ISSUE THREAD

**Issue by StavJi** [gcormier/tpms_silencer#2]
Please can you specify this components values for 433MHz Y2, C6, C9, C13, L2, C11, L1, C8, R3, C7, C10, C12? I have discovered that my transmitted waveform is almost square wave instead of sine wave. (I have change mentioned components according to datasheet and maybe I missed something). Thanks.

**Comment by gcormier** [comment]
The values in the schematic are what I used for 315MHz.

![image](https://user-images.githubusercontent.com/8388983/99881893-91990b80-2bea-11eb-925c-942fe96fec30.png)

It looks like the datasheet has an error in the drawing. L1 should have different values for 433MHz according to the table. I'll have to update my schematic.

**Comment by StavJi** [comment]
L1 should be 680nH, L4 (L2 in yours schematic) 82nH and Y1 (Y2 in yours schematic) 13,560MHz. Is that correct?

**Comment by gcormier** [comment]
Yes I believe so. I'll see if I can update my annotations to match the same as the reference schematic.

**Comment by gcormier** [comment]
Updated schematic 

![image](https://user-images.githubusercontent.com/8388983/100101338-1de84000-2e30-11eb-9989-eeaad1b10803.png)
